#!/usr/bin/env bash
cd src; ln -sf PowerPC/{*.ml{,i},libmincaml.S} .; cd ..
cd test; ln -sf PowerPC/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf PowerPC/Makefile .; cd ..
cd bytemark; ln -sf PowerPC/Makefile .; cd ..
cd min-rt; ln -sf PowerPC/globals.s .; cd ..
