#!/usr/bin/env bash
cd src; ln -sf SPARC/{*.ml{,i},libmincaml.S} .; cd ..
cd test; ln -sf SPARC/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf SPARC/Makefile .; cd ..
cd bytemark; ln -sf SPARC/Makefile .; cd ..
cd min-rt; ln -sf SPARC/globals.s .; cd ..
