#!/usr/bin/env bash
echo "currently x86 backend doesn't work"
# cd src; ln -sf x86/{*.ml{,i},libmincaml.S} .; cd ..
# cd test; ln -sf x86/{,too}manyargs.ml .; cd ..
# cd shootout; ln -sf x86/Makefile .; cd ..